### PR TITLE
chore!: rename optional dependency

### PR DESCRIPTION
**Pull request by korikuzma**
* `tests` -> `test`

To be consistent with our other tools

### CODE REVIEW

**Review by jsstevenson — APPROVED** [review]

**Comment by jsstevenson** [comment]
oh wait

**Comment by jsstevenson** [comment]
other way https://github.com/GenomicMedLab/software-templates/blob/2e814cf08285c8306b03208d2760bc569f9f4b32/python/%7B%7Bcookiecutter.project_slug%7D%7D/pyproject.toml#L25

**Comment by jsstevenson** [comment]
there are like 3 cases of 'test' that ive been meaning to change but the rest are 'tests'

**Comment by korikuzma** [comment]
Ope my bad. Though gene was updated. I can fix the others

**Pull request closed without merging**
